import "./globals.css";

import Navigation from "@/components/navigation";

export const metadata = {
  title: "My first NEXT APP",
  description: "Generated by create next app",
  keywords: 'Next, React, App, Project',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/vapor/bootstrap.min.css" />
      </head>
      <body>
        <Navigation />
        <div className="container p-4">
          {children}
        </div>
        </body>
    </html>
  );
}
