import "./globals.css";

import Navigation from "@/components/navigation";

export const metadata = {
  title: "My first NEXT APP",
  description: "Generated by create next app",
  keywords: 'Next, React, App, Project',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        </body>
    </html>
  );
}
